export const pois = [
    { "name": "Great coffee", "icon": "☕" },
    { "name": "Great tea selection", "icon": "🍵" },
    { "name": "Prepared foods", "icon": "🥪" },
    { "name": "Quick bite", "icon": "🍽️" },
    { "name": "Breakfast", "icon": "🍳" },
    { "name": "Brunch", "icon": "🥞" },
    { "name": "Lunch", "icon": "🥗" },
    { "name": "Dessert", "icon": "🍰" },
    { "name": "Seating", "icon": "🪑" },
    { "name": "Outdoor seating", "icon": "🌳" },
    { "name": "Casual", "icon": "👕" },
    { "name": "Cosy", "icon": "🏡" },
    { "name": "Trendy", "icon": "✨" },
    { "name": "Credit cards", "icon": "💳" },
    { "name": "Debit cards", "icon": "💳" },
    { "name": "NFC mobile payments", "icon": "📱" },
    { "name": "Tourists", "icon": "🌍" },
    { "name": "University students", "icon": "🎓" },
    { "name": "Wheelchair-accessible entrance", "icon": "♿" },
    { "name": "Wheelchair-accessible seating", "icon": "♿" },
    { "name": "Wheelchair-accessible toilet", "icon": "🚻" },
    { "name": "Identifies as women-owned", "icon": "🚺" },
    { "name": "Gender-neutral toilets", "icon": "🚻" },
    { "name": "LGBTQ+ friendly", "icon": "🏳️‍🌈" },
    { "name": "Toilets", "icon": "🚻" },
    { "name": "Solo dining", "icon": "🍽️" }
]
